version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - elk

  tracebeat:
    image: droxops/roxcomposer-tracebeat:0.0.1
    volumes:
      - ../logs:/usr/share/filebeat/watch/
    networks:
      - elk
    depends_on:
      - logstash

  connectorbeat:
    image: droxops/roxcomposer-connectorbeat:0.0.1
    volumes:
      - ../logs:/usr/share/filebeat/watch/
    networks:
      - elk
    depends_on:
      - logstash

  servicebeat:
    image: droxops/roxcomposer-servicebeat:0.0.1
    volumes:
      - ../logs:/usr/share/filebeat/watch/
    networks:
      - elk
    depends_on:
      - logstash

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config:/usr/share/logstash/config
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "8080:8080"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
