version: 2

services:
  tracebeat:
    image: docker.elastic.co/beats/filebeat:6.2.4
    volumes:
      - tracebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ../logs/trace.log:/usr/share/filebeat/trace.log
    networks:
      - elk
