version: '2'

services:
  tracebeat:
    image: droxops/roxcomposer-tracebeat:0.0.1
    volumes:
      - ../logs:/usr/share/filebeat/watch/
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/config/pipeline.yml:/usr/share/logstash/config/pipeline.yml
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "8080:8080"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
        #    depends_on:
        #      - elasticsearch

networks:
  elk:
    driver: bridge
