version: 2

services:
  tracebeat:
    image: docker.elastic.co/beats/filebeat:6.2.4
    volumes:
      - tracebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ../logs/trace.log:/usr/share/filebeat/trace.log
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config:/usr/share/logstash/config
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "8080:8080"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
