# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: droxops/mosaic-node-py:0.0.4

    working_directory: ~/repo

    steps:
      # checkout the code of the branch from github, which triggers the build
      - checkout

      - restore_cache:
          keys:
            - python-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - python-dependencies-
            - node-dependency-cache-{{ checksum "impress_plugin/package.json" }}
            - node-dependency-cache-

      - run:
          name: install python dependencies
          command: |
            python3.6 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

      - run:
          name: install node dependencies
          working_directory: impress_plugin
          command: npm install

      - save_cache:
          paths:
            - ./venv
          key: python-dependencies-{{ checksum "requirements.txt" }}

      - save_cache:
          key: node-dependency-cache-{{ checksum "impress_plugin/package.json" }}
          paths:
            - ./node_modules

      ### run automatic tests
      # python
      - run:
#          working_directory: ~/repo
          name: run python tests
          command: |
            . venv/bin/activate
            python3.6 setup.py test

      - run:
          name: locally install python package
          command: |
            . venv/bin/activate
            pip3.6 install -e .

      # run node tests
      - run:
          working_directory: impress_plugin
          name: run node tests
          command: |
            . venv/bin/activate
            npm test

      ### building
      # build package
#      - run:
##          working_directory: ~/repo
#          name: build archive
#          command: |
#            . venv/bin/activate
#            mkdir ./packages;
#            tar cz --exclude venv -f ./packages/build.tar.gz *;
      # build pip package
      - run:
          name: create pip package
          command: |
            . venv/bin/activate
            python3.6 setup.py sdist
            mkdir ./packages
            cp ./dist/*.tar.gz ./packages/
      # build demo package
      - run:
          name: create demo package
          command: |
            cd .circleci/mosaic-deploy
            ./build_mosaic.sh ../../../dist/*.tar.gz ../../../impress_plugin
            cp mosaic-demo-*.tar.gz ../../packages/

      ### artifacts
      # store artifact
      - store_artifacts:
          path: packages
          destination: packages

      ### deployment
      # deploy to gru
      - deploy:
          name: deploy to gru
          command: |
            scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./packages/mosaic*.tar.gz devpi@176.9.144.37:/tmp
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null devpi@176.9.144.37 'devpi login droxit --password=droxit; devpi use http://localhost:4040/droxit/dev; devpi upload /tmp/mosaic*.tar.gz; rm /tmp/mosaic*.tar.gz; devpi logoff'
            scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./packages/mosaic*.tar.gz devpi@176.9.144.37:/opt/mosaic-deploy/
