#!/bin/bash

server="localhost:7475"

### FUNCTIONS ###

function usage {
    echo "usage: mosaic-cli <COMMAND> [ARGUMENTS]"
    echo "commands:"
    echo "  deploy <SERVICE>"
    echo "  list_services"
    echo "  set_pipeline <NAME> <SERVICE> [...]"
    exit 0
}

function curl_post_file {
    header="Content-Type: application/json"
    path=$1
    argfile=$2
    curl -XPOST -H "$header" "http://$server/$path" -d "@$argfile"
}

function curl_post_data {
    header="Content-Type: application/json"
    path=$1
    args=$2
    curl -XPOST -H "$header" "http://$server/$path" -d "$args"
}

function curl_get {
    path=$1
    curl "http://$server/$path"
}

function deploy {
    if [[ ($# -lt 1) ]]
        then usage
    fi

    service="$1"
    
    argfile="services/$service.json"

    if [[ -e "$argfile" ]]
       then
          echo "deploying $service"
          curl_post_file "start_service" $argfile
       else
           echo "service file not found: $argfile"
           exit 1
    fi
}

function set_pipeline {
    if [[ ($# -lt 2) ]]
        then usage
    fi

    pname=$1
    shift
    if [[ ($# -eq 1) ]]
        then
            servarr="\"$1\""
        else
            servarr="\"$(echo -n $1; shift; printf "%s" "${@/#/'","'}")\""
    fi

    curl_post_data "set_pipeline" "{\"name\":\"$pname\",\"services\":[$servarr]}"
}


### EXECUTION ###
if [[ ($# -lt 1) ]]
    then usage
fi

case "$1" in
    "deploy")
        shift
        deploy $@
        ;;
    "set_pipeline")
        shift
        set_pipeline $@
        ;;
    "list_services")
        shift
        curl_get "services"
        ;;
    *)
        usage
        ;;
esac
