#! /usr/bin/env python3
# -*- coding: utf-8 -*-
#
# script mosaic-cli_old
#
# devs@droxit.de - droxIT GmbH
#
# Copyright (c) 2018 droxIT GmbH
#

import curses
import locale

locale.setlocale(locale.LC_ALL, '')
server = "localhost:7475"


def main(logwindow):
    curses.echo()

    logwindow.clear()

    height, width = logwindow.getmaxyx()

    logwindow.resize(height - 13, width)
    logwindow.border()
    logwindow.move(0, 2)
    logwindow.addstr("Log Window")
    logwindow.move(1, 1)
    logwindow.addstr("Height: "+str(height)+", Width: "+str(width))
    logwindow.move(2, 1)
    logwindow.refresh()

    cmdhistory_window = curses.newwin(height-3, width, 10, 0)
    cmdhistory_window.border()
    cmdhistory_window.move(0, 2)
    cmdhistory_window.addstr("Command History")
    cmdhistory_window.refresh()

    cmdhistory = curses.newpad(1000, width)
    cmdhistory_pos = 0
    cmdhistory.refresh(cmdhistory_pos, 0, 11, 1, height-4, width-2)

    cmdline = curses.newwin(3, width, height - 3, 0)
    cmdline.keypad(True)
    cmdline.border()
    cmdline.move(1, 1)
    cmdline.refresh()
    curses.doupdate()

    while True:
        # Char Handling
        y, x = cmdline.getyx()
        key = cmdline.getch(y, x)

        if key == curses.KEY_UP:
            if cmdhistory_pos > 0:
                cmdhistory_pos -= 1
        elif key == curses.KEY_DOWN:
            y, x = cmdhistory.getyx()
            if y > cmdhistory_pos+height-3-11:
                cmdhistory_pos += 1
        elif key == curses.KEY_BACKSPACE:
            y, x = cmdline.getyx()
            cmdline.delch(y, x)
            cmdline.insch(y, x, 32)
        elif key == curses.KEY_ENTER:
            input_str = cmdline.instr(1, 1)
            cmdhistory.addstr(input_str)
            cmdline.deleteln(1, 1)
            cmdline.move(1, 1)
            y, x = cmdhistory.getyx()
            cmdhistory.move(y + 1, 0)
            if y + 1 > cmdhistory_pos + height - 3 - 11:
                cmdhistory_pos = y + 3 + 11 - height + 1
        elif key in range(26, 126):
            cmdline.addch(1, x, key)
            cmdline.move(1, x+1)

        redraw(cmdline, cmdhistory, cmdhistory_pos, height, width)


def redraw(cmdline, cmdhistory, cmdhistory_pos, height, width):
    cmdline.border()
    cmdline.refresh()
    cmdhistory.refresh(cmdhistory_pos, 0, 11, 1, height-4, width-2)
    curses.doupdate()


curses.wrapper(main)
