#! /usr/bin/env python3
#
# script mosaic-cli
#
# devs@droxit.de - droxIT GmbH
#
# Copyright (c) 2018 droxIT GmbH
#

import curses
server = "localhost:7475"


def main(logwindow):
    curses.echo()

    logwindow.clear()

    height, width = logwindow.getmaxyx()

    logwindow.resize(height - 13, width)
    logwindow.border()
    logwindow.move(0, 2)
    logwindow.addstr("Log Window")
    logwindow.move(1, 1)
    logwindow.addstr("Height: "+str(height)+", Width: "+str(width))
    logwindow.refresh()

    cmdhistory_window = curses.newwin(height-3, width, 10, 0)
    cmdhistory_window.border()
    cmdhistory_window.move(0, 2)
    cmdhistory_window.addstr("Command History")
    cmdhistory_window.refresh()

    cmdhistory = curses.newpad(1000, width)
    cmdhistory_pos = 0
    cmdhistory.refresh(cmdhistory_pos, 0, 11, 1, height-3, width-2)

    cmdline = curses.newwin(3, width, height - 3, 0)
    cmdline.keypad(True)
    cmdline.border()
    cmdline.refresh()
    curses.doupdate()

    while True:
        input_string = cmdline.getstr(1, 1)
        cmdline.clear()
        cmdline.border()
        cmdhistory.addstr(input_string)
        y, x = cmdhistory.getyx()
        cmdhistory.move(y + 1, 0)
        if(y+1 > height-3-cmdhistory_pos-11):
            cmdhistory_pos += 1
        cmdhistory.refresh(cmdhistory_pos, 0, 11, 1, height-3, width-2)
        curses.doupdate()


curses.wrapper(main)
