#! /usr/bin/env python3
#
# script mosaic-cli
#
# devs@droxit.de - droxIT GmbH
#
# Copyright (c) 2018 droxIT GmbH
#

import curses
server = "localhost:7475"


def main(logwindow):
    curses.echo()

    logwindow.clear()

    height, width = logwindow.getmaxyx()

    logwindow.resize(height - 13, width)
    logwindow.move(1, 1)
    logwindow.border()
    logwindow.refresh()

    cmdhistory = curses.newwin(13, width, height - 14, 0)
    cmdhistory.move(1, 1)
    cmdhistory.border()
    cmdhistory.refresh()

    cmdline = curses.newwin(3, width, height - 3, 0)
    cmdline.keypad(True)
    cmdline.border()
    cmdline.refresh()

    curses.doupdate()


    while(True):
        input_string = cmdline.getstr(1, 1)
        cmdline.clear()
        cmdline.border()
        cmdhistory.addstr(input_string)
        y, x = cmdhistory.getyx()
        cmdhistory.move(y + 1, 1)
        cmdhistory.refresh()
        curses.doupdate()


curses.wrapper(main)
