# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_com.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_com.proto',
  package='service_communication',
  syntax='proto3',
  serialized_pb=_b('\n\x11service_com.proto\x12\x15service_communication\"\x7f\n\rMosaicMessage\x12\x31\n\x08pipeline\x18\x01 \x01(\x0b\x32\x1f.service_communication.Pipeline\x12/\n\x07payload\x18\x02 \x01(\x0b\x32\x1e.service_communication.Payload\x12\n\n\x02id\x18\x03 \x01(\t\"<\n\x08Pipeline\x12\x30\n\x08services\x18\x01 \x03(\x0b\x32\x1e.service_communication.Service\"K\n\x07Service\x12\n\n\x02id\x18\x01 \x01(\t\x12\x34\n\nparameters\x18\x02 \x03(\x0b\x32 .service_communication.Parameter\"\"\n\tParameter\x12\x15\n\rserviceParams\x18\x01 \x01(\t\"\x17\n\x07Payload\x12\x0c\n\x04\x62ody\x18\x01 \x01(\tb\x06proto3')
)




_MOSAICMESSAGE = _descriptor.Descriptor(
  name='MosaicMessage',
  full_name='service_communication.MosaicMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pipeline', full_name='service_communication.MosaicMessage.pipeline', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='service_communication.MosaicMessage.payload', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='service_communication.MosaicMessage.id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=171,
)


_PIPELINE = _descriptor.Descriptor(
  name='Pipeline',
  full_name='service_communication.Pipeline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='services', full_name='service_communication.Pipeline.services', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=233,
)


_SERVICE = _descriptor.Descriptor(
  name='Service',
  full_name='service_communication.Service',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='service_communication.Service.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='service_communication.Service.parameters', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=310,
)


_PARAMETER = _descriptor.Descriptor(
  name='Parameter',
  full_name='service_communication.Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serviceParams', full_name='service_communication.Parameter.serviceParams', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=346,
)


_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='service_communication.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='service_communication.Payload.body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=371,
)

_MOSAICMESSAGE.fields_by_name['pipeline'].message_type = _PIPELINE
_MOSAICMESSAGE.fields_by_name['payload'].message_type = _PAYLOAD
_PIPELINE.fields_by_name['services'].message_type = _SERVICE
_SERVICE.fields_by_name['parameters'].message_type = _PARAMETER
DESCRIPTOR.message_types_by_name['MosaicMessage'] = _MOSAICMESSAGE
DESCRIPTOR.message_types_by_name['Pipeline'] = _PIPELINE
DESCRIPTOR.message_types_by_name['Service'] = _SERVICE
DESCRIPTOR.message_types_by_name['Parameter'] = _PARAMETER
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MosaicMessage = _reflection.GeneratedProtocolMessageType('MosaicMessage', (_message.Message,), dict(
  DESCRIPTOR = _MOSAICMESSAGE,
  __module__ = 'service_com_pb2'
  # @@protoc_insertion_point(class_scope:service_communication.MosaicMessage)
  ))
_sym_db.RegisterMessage(MosaicMessage)

Pipeline = _reflection.GeneratedProtocolMessageType('Pipeline', (_message.Message,), dict(
  DESCRIPTOR = _PIPELINE,
  __module__ = 'service_com_pb2'
  # @@protoc_insertion_point(class_scope:service_communication.Pipeline)
  ))
_sym_db.RegisterMessage(Pipeline)

Service = _reflection.GeneratedProtocolMessageType('Service', (_message.Message,), dict(
  DESCRIPTOR = _SERVICE,
  __module__ = 'service_com_pb2'
  # @@protoc_insertion_point(class_scope:service_communication.Service)
  ))
_sym_db.RegisterMessage(Service)

Parameter = _reflection.GeneratedProtocolMessageType('Parameter', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETER,
  __module__ = 'service_com_pb2'
  # @@protoc_insertion_point(class_scope:service_communication.Parameter)
  ))
_sym_db.RegisterMessage(Parameter)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOAD,
  __module__ = 'service_com_pb2'
  # @@protoc_insertion_point(class_scope:service_communication.Payload)
  ))
_sym_db.RegisterMessage(Payload)


# @@protoc_insertion_point(module_scope)
